<project>
	<modelVersion>4.0.0</modelVersion>
	<groupId>42projet</groupId>
	<artifactId>swingy</artifactId>
	<version>0.1</version>
	<packaging>jar</packaging>

	<profiles>
			<profile>
				<id>java-21</id>
				<activation>
					<jdk>21</jdk>
				</activation>
				<properties>
					<maven.compiler.source>21</maven.compiler.source>
					<maven.compiler.target>21</maven.compiler.target>
				</properties>
			</profile>

			<profile>
				<id>java-25</id>
				<activation>
					<jdk>25</jdk>
				</activation>
				<properties>
					<maven.compiler.source>25</maven.compiler.source>
					<maven.compiler.target>25</maven.compiler.target>
				</properties>
			</profile>
		</profiles>

	<build>
		<defaultGoal>clean package</defaultGoal>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.4.1</version>
				<configuration>
					<archive>
						<manifest>
							<mainClass>Main</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
